#!/usr/bin/env bash
# Script to display information about subdomains for a given domain

display_subdomain_info() {
    local subdomain="$1"
    local record_type=$(dig "$subdomain.$domain" +short | awk '/^[^;]/ {print $4; exit}')
    local destination=$(dig "$subdomain.$domain" +short | awk '/^[^;]/ {print $5; exit}')

    if [ -n "$record_type" ] && [ -n "$destination" ]; then
        echo "The subdomain $subdomain is a $record_type record and points to $destination"
    fi
}

domain="$1"

if [ -z "$2" ]; then
    display_subdomain_info "www"
    display_subdomain_info "lb-01"
    display_subdomain_info "web-01"
    display_subdomain_info "web-02"
else
    subdomain="$2"
    display_subdomain_info "$subdomain"
fi
