#!/usr/bin/env bash
# Install and configure Nginx web server

# Update package lists
apt-get update

# Install Nginx
apt-get install -y nginx

# Create a new index.html file
echo "Hello World!" > /var/www/html/index.html

# Check if Nginx is running, and start it if not
if ! pgrep -x "nginx" > /dev/null; then
    service nginx start
else
    # Reload Nginx configuration
    service nginx reload
fi
